# Generated by Django 6.0.1 on 2026-01-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration_days', models.PositiveIntegerField()),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overview', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='safaris.destination')),
            ],
        ),
    ]
