# Generated by Django 5.2.4 on 2026-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0003_alter_destination_id_alter_safaripackage_id_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='safari_packages', to='safaris.place'),
        ),
    ]
