# Generated by Django 5.2.4 on 2026-01-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0005_place_image_alter_destination_id_alter_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
