# Generated by Django 5.2.4 on 2026-01-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0006_alter_destination_id_alter_place_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaripackage',
            name='base_price_usd',
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='safaris/'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safari_packages', to='safaris.destination'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
